import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffeeee',
  },
  input: {
    height: 50,
    width: '100%',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    fontSize: 16,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginVertical: 5,
    paddingVertical: 10,
    color: '#333',
  },
  item: {
    padding: 10,
    fontSize: 18,
    height: 44,
    color: '#000',
    borderBottomWidth: 1,
    borderColor: 'rgba(0,0,0,0.2)',
  },
  headerContainer: {
    height: 55,
    backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  headderText: {
    flex: 1,
    color: '#fff',
    fontSize: 20,
    paddingHorizontal: 12,
    fontWeight: '600',
  },
  sectionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    borderRadius: 5,
    overflow: 'hidden',
  },

  quantityContaine: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 20,
    height: 50,
    justifyContent: 'space-between',
    flex: 1,
    backgroundColor: '#ffff',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: 'rgba(0,0,0,0.2)',
    paddingHorizontal: 10,
  },
  priceContainer: {
    backgroundColor: '#f5f5f5',
    height: 50,
    flex: 0.7,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    borderRadius: 5,
  },
  text: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  text2: {color: '#000', fontSize: 20, fontWeight: 'bold'},
  productContainer: {
    padding: 10,
    borderRadius: 5,
    backgroundColor: '#b3e1b5',
    marginBottom: 2,
  },
  grandTotal: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: '#fff',
    padding: 5,
    marginVertical: 10,
    borderRadius: 5,
  },
});
